ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: 5432
      user: ecommerce_user
      pass: ecommerce_pass
      dbname: ecommerce
      schema: analytics
